### ISSUE TITLE
Use 'hydrate' instead of 'render' on client, when SSR is enabled

### ISSUE THREAD

**Issue by gersomvg** [JBostelaar/react-prime#3]
https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67

**Comment by JBostelaar** [comment]
Thanks for the feedback, it's fixed now: https://github.com/JBostelaar/react-redux-boilerplate/commit/240219c02d46280a8a84da10a2324eec2891411b
