### ISSUE TITLE
Use targets: { node: 'current' } for babel-preset-env on server

### ISSUE THREAD

**Issue by gersomvg** [JBostelaar/react-prime#4]
The server bundle is compiled with the default babel-preset-env, that targets browsers by default. This can be solved by removing the babel config from the package.json and specifying it separately for the `webpack.config(.prod).js` file and the `webpack.config.server.js` file.

**Comment by rnnyrk** [comment]
Resolved? @JBostelaar 
https://github.com/JBostelaar/react-prime/pull/6
